package com.kylin.quantization.mapper;

import com.kylin.quantization.model.Fund;
import com.kylin.quantization.model.FundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    long countByExample(FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    int deleteByExample(FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    int insert(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    int insertSelective(Fund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    List<Fund> selectByExample(FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fund record, @Param("example") FundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    int updateByExample(@Param("record") Fund record, @Param("example") FundExample example);

    List<Fund> searchTips(String searchWord);
}