package com.kylin.quantization.model;

import java.math.BigDecimal;

public class CorrIndex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORR_INDEX.index1
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    private String index1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORR_INDEX.index2
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    private String index2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CORR_INDEX.corrratio
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    private BigDecimal corrratio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORR_INDEX.index1
     *
     * @return the value of CORR_INDEX.index1
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    public String getIndex1() {
        return index1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORR_INDEX.index1
     *
     * @param index1 the value for CORR_INDEX.index1
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    public void setIndex1(String index1) {
        this.index1 = index1 == null ? null : index1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORR_INDEX.index2
     *
     * @return the value of CORR_INDEX.index2
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    public String getIndex2() {
        return index2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORR_INDEX.index2
     *
     * @param index2 the value for CORR_INDEX.index2
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    public void setIndex2(String index2) {
        this.index2 = index2 == null ? null : index2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CORR_INDEX.corrratio
     *
     * @return the value of CORR_INDEX.corrratio
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    public BigDecimal getCorrratio() {
        return corrratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CORR_INDEX.corrratio
     *
     * @param corrratio the value for CORR_INDEX.corrratio
     *
     * @mbg.generated Wed Jan 30 18:22:48 CST 2019
     */
    public void setCorrratio(BigDecimal corrratio) {
        this.corrratio = corrratio;
    }
}