package com.kylin.quantization.model;

public class Fund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.rowkey
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String rowkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.fundcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String fundcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.fundtype
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String fundtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.tgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String tgfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.zgrgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String zgrgfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.bbms
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String bbms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.glfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String glfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.clylfh
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String clylfh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.yjbjjz
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String yjbjjz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.fhgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String fhgm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.gzbd
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String gzbd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.zcgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String zcgm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.zjbbq
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String zjbbq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.fxrq
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String fxrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.jjtgr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String jjtgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.jjqc
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String jjqc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.zgshfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String zgshfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.jjjc
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String jjjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.jjlx
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String jjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.jjglr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String jjglr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.zgsgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String zgsgfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.xsfwfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String xsfwfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.dbjg
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String dbjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.jjdm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String jjdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.clrqgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String clrqgm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FUND.jjjlr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String jjjlr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.rowkey
     *
     * @return the value of FUND.rowkey
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getRowkey() {
        return rowkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.rowkey
     *
     * @param rowkey the value for FUND.rowkey
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setRowkey(String rowkey) {
        this.rowkey = rowkey == null ? null : rowkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.fundcode
     *
     * @return the value of FUND.fundcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getFundcode() {
        return fundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.fundcode
     *
     * @param fundcode the value for FUND.fundcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setFundcode(String fundcode) {
        this.fundcode = fundcode == null ? null : fundcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.fundtype
     *
     * @return the value of FUND.fundtype
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getFundtype() {
        return fundtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.fundtype
     *
     * @param fundtype the value for FUND.fundtype
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setFundtype(String fundtype) {
        this.fundtype = fundtype == null ? null : fundtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.tgfl
     *
     * @return the value of FUND.tgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getTgfl() {
        return tgfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.tgfl
     *
     * @param tgfl the value for FUND.tgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setTgfl(String tgfl) {
        this.tgfl = tgfl == null ? null : tgfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.zgrgfl
     *
     * @return the value of FUND.zgrgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getZgrgfl() {
        return zgrgfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.zgrgfl
     *
     * @param zgrgfl the value for FUND.zgrgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setZgrgfl(String zgrgfl) {
        this.zgrgfl = zgrgfl == null ? null : zgrgfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.bbms
     *
     * @return the value of FUND.bbms
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getBbms() {
        return bbms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.bbms
     *
     * @param bbms the value for FUND.bbms
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setBbms(String bbms) {
        this.bbms = bbms == null ? null : bbms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.glfl
     *
     * @return the value of FUND.glfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getGlfl() {
        return glfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.glfl
     *
     * @param glfl the value for FUND.glfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setGlfl(String glfl) {
        this.glfl = glfl == null ? null : glfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.clylfh
     *
     * @return the value of FUND.clylfh
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getClylfh() {
        return clylfh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.clylfh
     *
     * @param clylfh the value for FUND.clylfh
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setClylfh(String clylfh) {
        this.clylfh = clylfh == null ? null : clylfh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.yjbjjz
     *
     * @return the value of FUND.yjbjjz
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getYjbjjz() {
        return yjbjjz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.yjbjjz
     *
     * @param yjbjjz the value for FUND.yjbjjz
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setYjbjjz(String yjbjjz) {
        this.yjbjjz = yjbjjz == null ? null : yjbjjz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.fhgm
     *
     * @return the value of FUND.fhgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getFhgm() {
        return fhgm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.fhgm
     *
     * @param fhgm the value for FUND.fhgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setFhgm(String fhgm) {
        this.fhgm = fhgm == null ? null : fhgm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.gzbd
     *
     * @return the value of FUND.gzbd
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getGzbd() {
        return gzbd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.gzbd
     *
     * @param gzbd the value for FUND.gzbd
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setGzbd(String gzbd) {
        this.gzbd = gzbd == null ? null : gzbd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.zcgm
     *
     * @return the value of FUND.zcgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getZcgm() {
        return zcgm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.zcgm
     *
     * @param zcgm the value for FUND.zcgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setZcgm(String zcgm) {
        this.zcgm = zcgm == null ? null : zcgm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.zjbbq
     *
     * @return the value of FUND.zjbbq
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getZjbbq() {
        return zjbbq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.zjbbq
     *
     * @param zjbbq the value for FUND.zjbbq
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setZjbbq(String zjbbq) {
        this.zjbbq = zjbbq == null ? null : zjbbq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.fxrq
     *
     * @return the value of FUND.fxrq
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getFxrq() {
        return fxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.fxrq
     *
     * @param fxrq the value for FUND.fxrq
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setFxrq(String fxrq) {
        this.fxrq = fxrq == null ? null : fxrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.jjtgr
     *
     * @return the value of FUND.jjtgr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getJjtgr() {
        return jjtgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.jjtgr
     *
     * @param jjtgr the value for FUND.jjtgr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setJjtgr(String jjtgr) {
        this.jjtgr = jjtgr == null ? null : jjtgr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.jjqc
     *
     * @return the value of FUND.jjqc
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getJjqc() {
        return jjqc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.jjqc
     *
     * @param jjqc the value for FUND.jjqc
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setJjqc(String jjqc) {
        this.jjqc = jjqc == null ? null : jjqc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.zgshfl
     *
     * @return the value of FUND.zgshfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getZgshfl() {
        return zgshfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.zgshfl
     *
     * @param zgshfl the value for FUND.zgshfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setZgshfl(String zgshfl) {
        this.zgshfl = zgshfl == null ? null : zgshfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.jjjc
     *
     * @return the value of FUND.jjjc
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getJjjc() {
        return jjjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.jjjc
     *
     * @param jjjc the value for FUND.jjjc
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setJjjc(String jjjc) {
        this.jjjc = jjjc == null ? null : jjjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.jjlx
     *
     * @return the value of FUND.jjlx
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getJjlx() {
        return jjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.jjlx
     *
     * @param jjlx the value for FUND.jjlx
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setJjlx(String jjlx) {
        this.jjlx = jjlx == null ? null : jjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.jjglr
     *
     * @return the value of FUND.jjglr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getJjglr() {
        return jjglr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.jjglr
     *
     * @param jjglr the value for FUND.jjglr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setJjglr(String jjglr) {
        this.jjglr = jjglr == null ? null : jjglr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.zgsgfl
     *
     * @return the value of FUND.zgsgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getZgsgfl() {
        return zgsgfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.zgsgfl
     *
     * @param zgsgfl the value for FUND.zgsgfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setZgsgfl(String zgsgfl) {
        this.zgsgfl = zgsgfl == null ? null : zgsgfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.xsfwfl
     *
     * @return the value of FUND.xsfwfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getXsfwfl() {
        return xsfwfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.xsfwfl
     *
     * @param xsfwfl the value for FUND.xsfwfl
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setXsfwfl(String xsfwfl) {
        this.xsfwfl = xsfwfl == null ? null : xsfwfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.dbjg
     *
     * @return the value of FUND.dbjg
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getDbjg() {
        return dbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.dbjg
     *
     * @param dbjg the value for FUND.dbjg
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setDbjg(String dbjg) {
        this.dbjg = dbjg == null ? null : dbjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.jjdm
     *
     * @return the value of FUND.jjdm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getJjdm() {
        return jjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.jjdm
     *
     * @param jjdm the value for FUND.jjdm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setJjdm(String jjdm) {
        this.jjdm = jjdm == null ? null : jjdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.clrqgm
     *
     * @return the value of FUND.clrqgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getClrqgm() {
        return clrqgm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.clrqgm
     *
     * @param clrqgm the value for FUND.clrqgm
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setClrqgm(String clrqgm) {
        this.clrqgm = clrqgm == null ? null : clrqgm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FUND.jjjlr
     *
     * @return the value of FUND.jjjlr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getJjjlr() {
        return jjjlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FUND.jjjlr
     *
     * @param jjjlr the value for FUND.jjjlr
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setJjjlr(String jjjlr) {
        this.jjjlr = jjjlr == null ? null : jjjlr.trim();
    }
}