package com.kylin.quantization.model;

import java.util.ArrayList;
import java.util.List;

public class FundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public FundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRowkeyIsNull() {
            addCriterion("rowkey is null");
            return (Criteria) this;
        }

        public Criteria andRowkeyIsNotNull() {
            addCriterion("rowkey is not null");
            return (Criteria) this;
        }

        public Criteria andRowkeyEqualTo(String value) {
            addCriterion("rowkey =", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyNotEqualTo(String value) {
            addCriterion("rowkey <>", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyGreaterThan(String value) {
            addCriterion("rowkey >", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyGreaterThanOrEqualTo(String value) {
            addCriterion("rowkey >=", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyLessThan(String value) {
            addCriterion("rowkey <", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyLessThanOrEqualTo(String value) {
            addCriterion("rowkey <=", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyLike(String value) {
            addCriterion("rowkey like", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyNotLike(String value) {
            addCriterion("rowkey not like", value, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyIn(List<String> values) {
            addCriterion("rowkey in", values, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyNotIn(List<String> values) {
            addCriterion("rowkey not in", values, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyBetween(String value1, String value2) {
            addCriterion("rowkey between", value1, value2, "rowkey");
            return (Criteria) this;
        }

        public Criteria andRowkeyNotBetween(String value1, String value2) {
            addCriterion("rowkey not between", value1, value2, "rowkey");
            return (Criteria) this;
        }

        public Criteria andFundcodeIsNull() {
            addCriterion("fundcode is null");
            return (Criteria) this;
        }

        public Criteria andFundcodeIsNotNull() {
            addCriterion("fundcode is not null");
            return (Criteria) this;
        }

        public Criteria andFundcodeEqualTo(String value) {
            addCriterion("fundcode =", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotEqualTo(String value) {
            addCriterion("fundcode <>", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeGreaterThan(String value) {
            addCriterion("fundcode >", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeGreaterThanOrEqualTo(String value) {
            addCriterion("fundcode >=", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeLessThan(String value) {
            addCriterion("fundcode <", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeLessThanOrEqualTo(String value) {
            addCriterion("fundcode <=", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeLike(String value) {
            addCriterion("fundcode like", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotLike(String value) {
            addCriterion("fundcode not like", value, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeIn(List<String> values) {
            addCriterion("fundcode in", values, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotIn(List<String> values) {
            addCriterion("fundcode not in", values, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeBetween(String value1, String value2) {
            addCriterion("fundcode between", value1, value2, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundcodeNotBetween(String value1, String value2) {
            addCriterion("fundcode not between", value1, value2, "fundcode");
            return (Criteria) this;
        }

        public Criteria andFundtypeIsNull() {
            addCriterion("fundtype is null");
            return (Criteria) this;
        }

        public Criteria andFundtypeIsNotNull() {
            addCriterion("fundtype is not null");
            return (Criteria) this;
        }

        public Criteria andFundtypeEqualTo(String value) {
            addCriterion("fundtype =", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotEqualTo(String value) {
            addCriterion("fundtype <>", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeGreaterThan(String value) {
            addCriterion("fundtype >", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeGreaterThanOrEqualTo(String value) {
            addCriterion("fundtype >=", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeLessThan(String value) {
            addCriterion("fundtype <", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeLessThanOrEqualTo(String value) {
            addCriterion("fundtype <=", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeLike(String value) {
            addCriterion("fundtype like", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotLike(String value) {
            addCriterion("fundtype not like", value, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeIn(List<String> values) {
            addCriterion("fundtype in", values, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotIn(List<String> values) {
            addCriterion("fundtype not in", values, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeBetween(String value1, String value2) {
            addCriterion("fundtype between", value1, value2, "fundtype");
            return (Criteria) this;
        }

        public Criteria andFundtypeNotBetween(String value1, String value2) {
            addCriterion("fundtype not between", value1, value2, "fundtype");
            return (Criteria) this;
        }

        public Criteria andTgflIsNull() {
            addCriterion("tgfl is null");
            return (Criteria) this;
        }

        public Criteria andTgflIsNotNull() {
            addCriterion("tgfl is not null");
            return (Criteria) this;
        }

        public Criteria andTgflEqualTo(String value) {
            addCriterion("tgfl =", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflNotEqualTo(String value) {
            addCriterion("tgfl <>", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflGreaterThan(String value) {
            addCriterion("tgfl >", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflGreaterThanOrEqualTo(String value) {
            addCriterion("tgfl >=", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflLessThan(String value) {
            addCriterion("tgfl <", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflLessThanOrEqualTo(String value) {
            addCriterion("tgfl <=", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflLike(String value) {
            addCriterion("tgfl like", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflNotLike(String value) {
            addCriterion("tgfl not like", value, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflIn(List<String> values) {
            addCriterion("tgfl in", values, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflNotIn(List<String> values) {
            addCriterion("tgfl not in", values, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflBetween(String value1, String value2) {
            addCriterion("tgfl between", value1, value2, "tgfl");
            return (Criteria) this;
        }

        public Criteria andTgflNotBetween(String value1, String value2) {
            addCriterion("tgfl not between", value1, value2, "tgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflIsNull() {
            addCriterion("zgrgfl is null");
            return (Criteria) this;
        }

        public Criteria andZgrgflIsNotNull() {
            addCriterion("zgrgfl is not null");
            return (Criteria) this;
        }

        public Criteria andZgrgflEqualTo(String value) {
            addCriterion("zgrgfl =", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflNotEqualTo(String value) {
            addCriterion("zgrgfl <>", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflGreaterThan(String value) {
            addCriterion("zgrgfl >", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflGreaterThanOrEqualTo(String value) {
            addCriterion("zgrgfl >=", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflLessThan(String value) {
            addCriterion("zgrgfl <", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflLessThanOrEqualTo(String value) {
            addCriterion("zgrgfl <=", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflLike(String value) {
            addCriterion("zgrgfl like", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflNotLike(String value) {
            addCriterion("zgrgfl not like", value, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflIn(List<String> values) {
            addCriterion("zgrgfl in", values, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflNotIn(List<String> values) {
            addCriterion("zgrgfl not in", values, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflBetween(String value1, String value2) {
            addCriterion("zgrgfl between", value1, value2, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andZgrgflNotBetween(String value1, String value2) {
            addCriterion("zgrgfl not between", value1, value2, "zgrgfl");
            return (Criteria) this;
        }

        public Criteria andBbmsIsNull() {
            addCriterion("bbms is null");
            return (Criteria) this;
        }

        public Criteria andBbmsIsNotNull() {
            addCriterion("bbms is not null");
            return (Criteria) this;
        }

        public Criteria andBbmsEqualTo(String value) {
            addCriterion("bbms =", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsNotEqualTo(String value) {
            addCriterion("bbms <>", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsGreaterThan(String value) {
            addCriterion("bbms >", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsGreaterThanOrEqualTo(String value) {
            addCriterion("bbms >=", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsLessThan(String value) {
            addCriterion("bbms <", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsLessThanOrEqualTo(String value) {
            addCriterion("bbms <=", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsLike(String value) {
            addCriterion("bbms like", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsNotLike(String value) {
            addCriterion("bbms not like", value, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsIn(List<String> values) {
            addCriterion("bbms in", values, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsNotIn(List<String> values) {
            addCriterion("bbms not in", values, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsBetween(String value1, String value2) {
            addCriterion("bbms between", value1, value2, "bbms");
            return (Criteria) this;
        }

        public Criteria andBbmsNotBetween(String value1, String value2) {
            addCriterion("bbms not between", value1, value2, "bbms");
            return (Criteria) this;
        }

        public Criteria andGlflIsNull() {
            addCriterion("glfl is null");
            return (Criteria) this;
        }

        public Criteria andGlflIsNotNull() {
            addCriterion("glfl is not null");
            return (Criteria) this;
        }

        public Criteria andGlflEqualTo(String value) {
            addCriterion("glfl =", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflNotEqualTo(String value) {
            addCriterion("glfl <>", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflGreaterThan(String value) {
            addCriterion("glfl >", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflGreaterThanOrEqualTo(String value) {
            addCriterion("glfl >=", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflLessThan(String value) {
            addCriterion("glfl <", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflLessThanOrEqualTo(String value) {
            addCriterion("glfl <=", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflLike(String value) {
            addCriterion("glfl like", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflNotLike(String value) {
            addCriterion("glfl not like", value, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflIn(List<String> values) {
            addCriterion("glfl in", values, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflNotIn(List<String> values) {
            addCriterion("glfl not in", values, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflBetween(String value1, String value2) {
            addCriterion("glfl between", value1, value2, "glfl");
            return (Criteria) this;
        }

        public Criteria andGlflNotBetween(String value1, String value2) {
            addCriterion("glfl not between", value1, value2, "glfl");
            return (Criteria) this;
        }

        public Criteria andClylfhIsNull() {
            addCriterion("clylfh is null");
            return (Criteria) this;
        }

        public Criteria andClylfhIsNotNull() {
            addCriterion("clylfh is not null");
            return (Criteria) this;
        }

        public Criteria andClylfhEqualTo(String value) {
            addCriterion("clylfh =", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhNotEqualTo(String value) {
            addCriterion("clylfh <>", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhGreaterThan(String value) {
            addCriterion("clylfh >", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhGreaterThanOrEqualTo(String value) {
            addCriterion("clylfh >=", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhLessThan(String value) {
            addCriterion("clylfh <", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhLessThanOrEqualTo(String value) {
            addCriterion("clylfh <=", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhLike(String value) {
            addCriterion("clylfh like", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhNotLike(String value) {
            addCriterion("clylfh not like", value, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhIn(List<String> values) {
            addCriterion("clylfh in", values, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhNotIn(List<String> values) {
            addCriterion("clylfh not in", values, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhBetween(String value1, String value2) {
            addCriterion("clylfh between", value1, value2, "clylfh");
            return (Criteria) this;
        }

        public Criteria andClylfhNotBetween(String value1, String value2) {
            addCriterion("clylfh not between", value1, value2, "clylfh");
            return (Criteria) this;
        }

        public Criteria andYjbjjzIsNull() {
            addCriterion("yjbjjz is null");
            return (Criteria) this;
        }

        public Criteria andYjbjjzIsNotNull() {
            addCriterion("yjbjjz is not null");
            return (Criteria) this;
        }

        public Criteria andYjbjjzEqualTo(String value) {
            addCriterion("yjbjjz =", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzNotEqualTo(String value) {
            addCriterion("yjbjjz <>", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzGreaterThan(String value) {
            addCriterion("yjbjjz >", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzGreaterThanOrEqualTo(String value) {
            addCriterion("yjbjjz >=", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzLessThan(String value) {
            addCriterion("yjbjjz <", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzLessThanOrEqualTo(String value) {
            addCriterion("yjbjjz <=", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzLike(String value) {
            addCriterion("yjbjjz like", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzNotLike(String value) {
            addCriterion("yjbjjz not like", value, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzIn(List<String> values) {
            addCriterion("yjbjjz in", values, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzNotIn(List<String> values) {
            addCriterion("yjbjjz not in", values, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzBetween(String value1, String value2) {
            addCriterion("yjbjjz between", value1, value2, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andYjbjjzNotBetween(String value1, String value2) {
            addCriterion("yjbjjz not between", value1, value2, "yjbjjz");
            return (Criteria) this;
        }

        public Criteria andFhgmIsNull() {
            addCriterion("fhgm is null");
            return (Criteria) this;
        }

        public Criteria andFhgmIsNotNull() {
            addCriterion("fhgm is not null");
            return (Criteria) this;
        }

        public Criteria andFhgmEqualTo(String value) {
            addCriterion("fhgm =", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmNotEqualTo(String value) {
            addCriterion("fhgm <>", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmGreaterThan(String value) {
            addCriterion("fhgm >", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmGreaterThanOrEqualTo(String value) {
            addCriterion("fhgm >=", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmLessThan(String value) {
            addCriterion("fhgm <", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmLessThanOrEqualTo(String value) {
            addCriterion("fhgm <=", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmLike(String value) {
            addCriterion("fhgm like", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmNotLike(String value) {
            addCriterion("fhgm not like", value, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmIn(List<String> values) {
            addCriterion("fhgm in", values, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmNotIn(List<String> values) {
            addCriterion("fhgm not in", values, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmBetween(String value1, String value2) {
            addCriterion("fhgm between", value1, value2, "fhgm");
            return (Criteria) this;
        }

        public Criteria andFhgmNotBetween(String value1, String value2) {
            addCriterion("fhgm not between", value1, value2, "fhgm");
            return (Criteria) this;
        }

        public Criteria andGzbdIsNull() {
            addCriterion("gzbd is null");
            return (Criteria) this;
        }

        public Criteria andGzbdIsNotNull() {
            addCriterion("gzbd is not null");
            return (Criteria) this;
        }

        public Criteria andGzbdEqualTo(String value) {
            addCriterion("gzbd =", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdNotEqualTo(String value) {
            addCriterion("gzbd <>", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdGreaterThan(String value) {
            addCriterion("gzbd >", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdGreaterThanOrEqualTo(String value) {
            addCriterion("gzbd >=", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdLessThan(String value) {
            addCriterion("gzbd <", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdLessThanOrEqualTo(String value) {
            addCriterion("gzbd <=", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdLike(String value) {
            addCriterion("gzbd like", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdNotLike(String value) {
            addCriterion("gzbd not like", value, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdIn(List<String> values) {
            addCriterion("gzbd in", values, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdNotIn(List<String> values) {
            addCriterion("gzbd not in", values, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdBetween(String value1, String value2) {
            addCriterion("gzbd between", value1, value2, "gzbd");
            return (Criteria) this;
        }

        public Criteria andGzbdNotBetween(String value1, String value2) {
            addCriterion("gzbd not between", value1, value2, "gzbd");
            return (Criteria) this;
        }

        public Criteria andZcgmIsNull() {
            addCriterion("zcgm is null");
            return (Criteria) this;
        }

        public Criteria andZcgmIsNotNull() {
            addCriterion("zcgm is not null");
            return (Criteria) this;
        }

        public Criteria andZcgmEqualTo(String value) {
            addCriterion("zcgm =", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmNotEqualTo(String value) {
            addCriterion("zcgm <>", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmGreaterThan(String value) {
            addCriterion("zcgm >", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmGreaterThanOrEqualTo(String value) {
            addCriterion("zcgm >=", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmLessThan(String value) {
            addCriterion("zcgm <", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmLessThanOrEqualTo(String value) {
            addCriterion("zcgm <=", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmLike(String value) {
            addCriterion("zcgm like", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmNotLike(String value) {
            addCriterion("zcgm not like", value, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmIn(List<String> values) {
            addCriterion("zcgm in", values, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmNotIn(List<String> values) {
            addCriterion("zcgm not in", values, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmBetween(String value1, String value2) {
            addCriterion("zcgm between", value1, value2, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZcgmNotBetween(String value1, String value2) {
            addCriterion("zcgm not between", value1, value2, "zcgm");
            return (Criteria) this;
        }

        public Criteria andZjbbqIsNull() {
            addCriterion("zjbbq is null");
            return (Criteria) this;
        }

        public Criteria andZjbbqIsNotNull() {
            addCriterion("zjbbq is not null");
            return (Criteria) this;
        }

        public Criteria andZjbbqEqualTo(String value) {
            addCriterion("zjbbq =", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqNotEqualTo(String value) {
            addCriterion("zjbbq <>", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqGreaterThan(String value) {
            addCriterion("zjbbq >", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqGreaterThanOrEqualTo(String value) {
            addCriterion("zjbbq >=", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqLessThan(String value) {
            addCriterion("zjbbq <", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqLessThanOrEqualTo(String value) {
            addCriterion("zjbbq <=", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqLike(String value) {
            addCriterion("zjbbq like", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqNotLike(String value) {
            addCriterion("zjbbq not like", value, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqIn(List<String> values) {
            addCriterion("zjbbq in", values, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqNotIn(List<String> values) {
            addCriterion("zjbbq not in", values, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqBetween(String value1, String value2) {
            addCriterion("zjbbq between", value1, value2, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andZjbbqNotBetween(String value1, String value2) {
            addCriterion("zjbbq not between", value1, value2, "zjbbq");
            return (Criteria) this;
        }

        public Criteria andFxrqIsNull() {
            addCriterion("fxrq is null");
            return (Criteria) this;
        }

        public Criteria andFxrqIsNotNull() {
            addCriterion("fxrq is not null");
            return (Criteria) this;
        }

        public Criteria andFxrqEqualTo(String value) {
            addCriterion("fxrq =", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqNotEqualTo(String value) {
            addCriterion("fxrq <>", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqGreaterThan(String value) {
            addCriterion("fxrq >", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqGreaterThanOrEqualTo(String value) {
            addCriterion("fxrq >=", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqLessThan(String value) {
            addCriterion("fxrq <", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqLessThanOrEqualTo(String value) {
            addCriterion("fxrq <=", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqLike(String value) {
            addCriterion("fxrq like", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqNotLike(String value) {
            addCriterion("fxrq not like", value, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqIn(List<String> values) {
            addCriterion("fxrq in", values, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqNotIn(List<String> values) {
            addCriterion("fxrq not in", values, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqBetween(String value1, String value2) {
            addCriterion("fxrq between", value1, value2, "fxrq");
            return (Criteria) this;
        }

        public Criteria andFxrqNotBetween(String value1, String value2) {
            addCriterion("fxrq not between", value1, value2, "fxrq");
            return (Criteria) this;
        }

        public Criteria andJjtgrIsNull() {
            addCriterion("jjtgr is null");
            return (Criteria) this;
        }

        public Criteria andJjtgrIsNotNull() {
            addCriterion("jjtgr is not null");
            return (Criteria) this;
        }

        public Criteria andJjtgrEqualTo(String value) {
            addCriterion("jjtgr =", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrNotEqualTo(String value) {
            addCriterion("jjtgr <>", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrGreaterThan(String value) {
            addCriterion("jjtgr >", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrGreaterThanOrEqualTo(String value) {
            addCriterion("jjtgr >=", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrLessThan(String value) {
            addCriterion("jjtgr <", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrLessThanOrEqualTo(String value) {
            addCriterion("jjtgr <=", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrLike(String value) {
            addCriterion("jjtgr like", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrNotLike(String value) {
            addCriterion("jjtgr not like", value, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrIn(List<String> values) {
            addCriterion("jjtgr in", values, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrNotIn(List<String> values) {
            addCriterion("jjtgr not in", values, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrBetween(String value1, String value2) {
            addCriterion("jjtgr between", value1, value2, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjtgrNotBetween(String value1, String value2) {
            addCriterion("jjtgr not between", value1, value2, "jjtgr");
            return (Criteria) this;
        }

        public Criteria andJjqcIsNull() {
            addCriterion("jjqc is null");
            return (Criteria) this;
        }

        public Criteria andJjqcIsNotNull() {
            addCriterion("jjqc is not null");
            return (Criteria) this;
        }

        public Criteria andJjqcEqualTo(String value) {
            addCriterion("jjqc =", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcNotEqualTo(String value) {
            addCriterion("jjqc <>", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcGreaterThan(String value) {
            addCriterion("jjqc >", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcGreaterThanOrEqualTo(String value) {
            addCriterion("jjqc >=", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcLessThan(String value) {
            addCriterion("jjqc <", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcLessThanOrEqualTo(String value) {
            addCriterion("jjqc <=", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcLike(String value) {
            addCriterion("jjqc like", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcNotLike(String value) {
            addCriterion("jjqc not like", value, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcIn(List<String> values) {
            addCriterion("jjqc in", values, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcNotIn(List<String> values) {
            addCriterion("jjqc not in", values, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcBetween(String value1, String value2) {
            addCriterion("jjqc between", value1, value2, "jjqc");
            return (Criteria) this;
        }

        public Criteria andJjqcNotBetween(String value1, String value2) {
            addCriterion("jjqc not between", value1, value2, "jjqc");
            return (Criteria) this;
        }

        public Criteria andZgshflIsNull() {
            addCriterion("zgshfl is null");
            return (Criteria) this;
        }

        public Criteria andZgshflIsNotNull() {
            addCriterion("zgshfl is not null");
            return (Criteria) this;
        }

        public Criteria andZgshflEqualTo(String value) {
            addCriterion("zgshfl =", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflNotEqualTo(String value) {
            addCriterion("zgshfl <>", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflGreaterThan(String value) {
            addCriterion("zgshfl >", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflGreaterThanOrEqualTo(String value) {
            addCriterion("zgshfl >=", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflLessThan(String value) {
            addCriterion("zgshfl <", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflLessThanOrEqualTo(String value) {
            addCriterion("zgshfl <=", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflLike(String value) {
            addCriterion("zgshfl like", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflNotLike(String value) {
            addCriterion("zgshfl not like", value, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflIn(List<String> values) {
            addCriterion("zgshfl in", values, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflNotIn(List<String> values) {
            addCriterion("zgshfl not in", values, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflBetween(String value1, String value2) {
            addCriterion("zgshfl between", value1, value2, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andZgshflNotBetween(String value1, String value2) {
            addCriterion("zgshfl not between", value1, value2, "zgshfl");
            return (Criteria) this;
        }

        public Criteria andJjjcIsNull() {
            addCriterion("jjjc is null");
            return (Criteria) this;
        }

        public Criteria andJjjcIsNotNull() {
            addCriterion("jjjc is not null");
            return (Criteria) this;
        }

        public Criteria andJjjcEqualTo(String value) {
            addCriterion("jjjc =", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcNotEqualTo(String value) {
            addCriterion("jjjc <>", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcGreaterThan(String value) {
            addCriterion("jjjc >", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcGreaterThanOrEqualTo(String value) {
            addCriterion("jjjc >=", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcLessThan(String value) {
            addCriterion("jjjc <", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcLessThanOrEqualTo(String value) {
            addCriterion("jjjc <=", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcLike(String value) {
            addCriterion("jjjc like", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcNotLike(String value) {
            addCriterion("jjjc not like", value, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcIn(List<String> values) {
            addCriterion("jjjc in", values, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcNotIn(List<String> values) {
            addCriterion("jjjc not in", values, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcBetween(String value1, String value2) {
            addCriterion("jjjc between", value1, value2, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjjcNotBetween(String value1, String value2) {
            addCriterion("jjjc not between", value1, value2, "jjjc");
            return (Criteria) this;
        }

        public Criteria andJjlxIsNull() {
            addCriterion("jjlx is null");
            return (Criteria) this;
        }

        public Criteria andJjlxIsNotNull() {
            addCriterion("jjlx is not null");
            return (Criteria) this;
        }

        public Criteria andJjlxEqualTo(String value) {
            addCriterion("jjlx =", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxNotEqualTo(String value) {
            addCriterion("jjlx <>", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxGreaterThan(String value) {
            addCriterion("jjlx >", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxGreaterThanOrEqualTo(String value) {
            addCriterion("jjlx >=", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxLessThan(String value) {
            addCriterion("jjlx <", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxLessThanOrEqualTo(String value) {
            addCriterion("jjlx <=", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxLike(String value) {
            addCriterion("jjlx like", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxNotLike(String value) {
            addCriterion("jjlx not like", value, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxIn(List<String> values) {
            addCriterion("jjlx in", values, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxNotIn(List<String> values) {
            addCriterion("jjlx not in", values, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxBetween(String value1, String value2) {
            addCriterion("jjlx between", value1, value2, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjlxNotBetween(String value1, String value2) {
            addCriterion("jjlx not between", value1, value2, "jjlx");
            return (Criteria) this;
        }

        public Criteria andJjglrIsNull() {
            addCriterion("jjglr is null");
            return (Criteria) this;
        }

        public Criteria andJjglrIsNotNull() {
            addCriterion("jjglr is not null");
            return (Criteria) this;
        }

        public Criteria andJjglrEqualTo(String value) {
            addCriterion("jjglr =", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrNotEqualTo(String value) {
            addCriterion("jjglr <>", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrGreaterThan(String value) {
            addCriterion("jjglr >", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrGreaterThanOrEqualTo(String value) {
            addCriterion("jjglr >=", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrLessThan(String value) {
            addCriterion("jjglr <", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrLessThanOrEqualTo(String value) {
            addCriterion("jjglr <=", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrLike(String value) {
            addCriterion("jjglr like", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrNotLike(String value) {
            addCriterion("jjglr not like", value, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrIn(List<String> values) {
            addCriterion("jjglr in", values, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrNotIn(List<String> values) {
            addCriterion("jjglr not in", values, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrBetween(String value1, String value2) {
            addCriterion("jjglr between", value1, value2, "jjglr");
            return (Criteria) this;
        }

        public Criteria andJjglrNotBetween(String value1, String value2) {
            addCriterion("jjglr not between", value1, value2, "jjglr");
            return (Criteria) this;
        }

        public Criteria andZgsgflIsNull() {
            addCriterion("zgsgfl is null");
            return (Criteria) this;
        }

        public Criteria andZgsgflIsNotNull() {
            addCriterion("zgsgfl is not null");
            return (Criteria) this;
        }

        public Criteria andZgsgflEqualTo(String value) {
            addCriterion("zgsgfl =", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflNotEqualTo(String value) {
            addCriterion("zgsgfl <>", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflGreaterThan(String value) {
            addCriterion("zgsgfl >", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflGreaterThanOrEqualTo(String value) {
            addCriterion("zgsgfl >=", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflLessThan(String value) {
            addCriterion("zgsgfl <", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflLessThanOrEqualTo(String value) {
            addCriterion("zgsgfl <=", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflLike(String value) {
            addCriterion("zgsgfl like", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflNotLike(String value) {
            addCriterion("zgsgfl not like", value, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflIn(List<String> values) {
            addCriterion("zgsgfl in", values, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflNotIn(List<String> values) {
            addCriterion("zgsgfl not in", values, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflBetween(String value1, String value2) {
            addCriterion("zgsgfl between", value1, value2, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andZgsgflNotBetween(String value1, String value2) {
            addCriterion("zgsgfl not between", value1, value2, "zgsgfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflIsNull() {
            addCriterion("xsfwfl is null");
            return (Criteria) this;
        }

        public Criteria andXsfwflIsNotNull() {
            addCriterion("xsfwfl is not null");
            return (Criteria) this;
        }

        public Criteria andXsfwflEqualTo(String value) {
            addCriterion("xsfwfl =", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflNotEqualTo(String value) {
            addCriterion("xsfwfl <>", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflGreaterThan(String value) {
            addCriterion("xsfwfl >", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflGreaterThanOrEqualTo(String value) {
            addCriterion("xsfwfl >=", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflLessThan(String value) {
            addCriterion("xsfwfl <", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflLessThanOrEqualTo(String value) {
            addCriterion("xsfwfl <=", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflLike(String value) {
            addCriterion("xsfwfl like", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflNotLike(String value) {
            addCriterion("xsfwfl not like", value, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflIn(List<String> values) {
            addCriterion("xsfwfl in", values, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflNotIn(List<String> values) {
            addCriterion("xsfwfl not in", values, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflBetween(String value1, String value2) {
            addCriterion("xsfwfl between", value1, value2, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andXsfwflNotBetween(String value1, String value2) {
            addCriterion("xsfwfl not between", value1, value2, "xsfwfl");
            return (Criteria) this;
        }

        public Criteria andDbjgIsNull() {
            addCriterion("dbjg is null");
            return (Criteria) this;
        }

        public Criteria andDbjgIsNotNull() {
            addCriterion("dbjg is not null");
            return (Criteria) this;
        }

        public Criteria andDbjgEqualTo(String value) {
            addCriterion("dbjg =", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgNotEqualTo(String value) {
            addCriterion("dbjg <>", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgGreaterThan(String value) {
            addCriterion("dbjg >", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgGreaterThanOrEqualTo(String value) {
            addCriterion("dbjg >=", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgLessThan(String value) {
            addCriterion("dbjg <", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgLessThanOrEqualTo(String value) {
            addCriterion("dbjg <=", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgLike(String value) {
            addCriterion("dbjg like", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgNotLike(String value) {
            addCriterion("dbjg not like", value, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgIn(List<String> values) {
            addCriterion("dbjg in", values, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgNotIn(List<String> values) {
            addCriterion("dbjg not in", values, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgBetween(String value1, String value2) {
            addCriterion("dbjg between", value1, value2, "dbjg");
            return (Criteria) this;
        }

        public Criteria andDbjgNotBetween(String value1, String value2) {
            addCriterion("dbjg not between", value1, value2, "dbjg");
            return (Criteria) this;
        }

        public Criteria andJjdmIsNull() {
            addCriterion("jjdm is null");
            return (Criteria) this;
        }

        public Criteria andJjdmIsNotNull() {
            addCriterion("jjdm is not null");
            return (Criteria) this;
        }

        public Criteria andJjdmEqualTo(String value) {
            addCriterion("jjdm =", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmNotEqualTo(String value) {
            addCriterion("jjdm <>", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmGreaterThan(String value) {
            addCriterion("jjdm >", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmGreaterThanOrEqualTo(String value) {
            addCriterion("jjdm >=", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmLessThan(String value) {
            addCriterion("jjdm <", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmLessThanOrEqualTo(String value) {
            addCriterion("jjdm <=", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmLike(String value) {
            addCriterion("jjdm like", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmNotLike(String value) {
            addCriterion("jjdm not like", value, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmIn(List<String> values) {
            addCriterion("jjdm in", values, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmNotIn(List<String> values) {
            addCriterion("jjdm not in", values, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmBetween(String value1, String value2) {
            addCriterion("jjdm between", value1, value2, "jjdm");
            return (Criteria) this;
        }

        public Criteria andJjdmNotBetween(String value1, String value2) {
            addCriterion("jjdm not between", value1, value2, "jjdm");
            return (Criteria) this;
        }

        public Criteria andClrqgmIsNull() {
            addCriterion("clrqgm is null");
            return (Criteria) this;
        }

        public Criteria andClrqgmIsNotNull() {
            addCriterion("clrqgm is not null");
            return (Criteria) this;
        }

        public Criteria andClrqgmEqualTo(String value) {
            addCriterion("clrqgm =", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmNotEqualTo(String value) {
            addCriterion("clrqgm <>", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmGreaterThan(String value) {
            addCriterion("clrqgm >", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmGreaterThanOrEqualTo(String value) {
            addCriterion("clrqgm >=", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmLessThan(String value) {
            addCriterion("clrqgm <", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmLessThanOrEqualTo(String value) {
            addCriterion("clrqgm <=", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmLike(String value) {
            addCriterion("clrqgm like", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmNotLike(String value) {
            addCriterion("clrqgm not like", value, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmIn(List<String> values) {
            addCriterion("clrqgm in", values, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmNotIn(List<String> values) {
            addCriterion("clrqgm not in", values, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmBetween(String value1, String value2) {
            addCriterion("clrqgm between", value1, value2, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andClrqgmNotBetween(String value1, String value2) {
            addCriterion("clrqgm not between", value1, value2, "clrqgm");
            return (Criteria) this;
        }

        public Criteria andJjjlrIsNull() {
            addCriterion("jjjlr is null");
            return (Criteria) this;
        }

        public Criteria andJjjlrIsNotNull() {
            addCriterion("jjjlr is not null");
            return (Criteria) this;
        }

        public Criteria andJjjlrEqualTo(String value) {
            addCriterion("jjjlr =", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrNotEqualTo(String value) {
            addCriterion("jjjlr <>", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrGreaterThan(String value) {
            addCriterion("jjjlr >", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrGreaterThanOrEqualTo(String value) {
            addCriterion("jjjlr >=", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrLessThan(String value) {
            addCriterion("jjjlr <", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrLessThanOrEqualTo(String value) {
            addCriterion("jjjlr <=", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrLike(String value) {
            addCriterion("jjjlr like", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrNotLike(String value) {
            addCriterion("jjjlr not like", value, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrIn(List<String> values) {
            addCriterion("jjjlr in", values, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrNotIn(List<String> values) {
            addCriterion("jjjlr not in", values, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrBetween(String value1, String value2) {
            addCriterion("jjjlr between", value1, value2, "jjjlr");
            return (Criteria) this;
        }

        public Criteria andJjjlrNotBetween(String value1, String value2) {
            addCriterion("jjjlr not between", value1, value2, "jjjlr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FUND
     *
     * @mbg.generated do_not_delete_during_merge Fri Jan 25 16:07:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FUND
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}