package com.kylin.quantization.model;

import java.math.BigDecimal;

public class IndexFundCorr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEX_FUND_CORR.fundcode
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    private String fundcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEX_FUND_CORR.indexcode
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    private String indexcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEX_FUND_CORR.correlationindex
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    private BigDecimal correlationindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEX_FUND_CORR.corrtype
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    private Integer corrtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEX_FUND_CORR.fundcode
     *
     * @return the value of INDEX_FUND_CORR.fundcode
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public String getFundcode() {
        return fundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEX_FUND_CORR.fundcode
     *
     * @param fundcode the value for INDEX_FUND_CORR.fundcode
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public void setFundcode(String fundcode) {
        this.fundcode = fundcode == null ? null : fundcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEX_FUND_CORR.indexcode
     *
     * @return the value of INDEX_FUND_CORR.indexcode
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public String getIndexcode() {
        return indexcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEX_FUND_CORR.indexcode
     *
     * @param indexcode the value for INDEX_FUND_CORR.indexcode
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public void setIndexcode(String indexcode) {
        this.indexcode = indexcode == null ? null : indexcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEX_FUND_CORR.correlationindex
     *
     * @return the value of INDEX_FUND_CORR.correlationindex
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public BigDecimal getCorrelationindex() {
        return correlationindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEX_FUND_CORR.correlationindex
     *
     * @param correlationindex the value for INDEX_FUND_CORR.correlationindex
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public void setCorrelationindex(BigDecimal correlationindex) {
        this.correlationindex = correlationindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEX_FUND_CORR.corrtype
     *
     * @return the value of INDEX_FUND_CORR.corrtype
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public Integer getCorrtype() {
        return corrtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEX_FUND_CORR.corrtype
     *
     * @param corrtype the value for INDEX_FUND_CORR.corrtype
     *
     * @mbg.generated Sun Jan 27 16:36:53 CST 2019
     */
    public void setCorrtype(Integer corrtype) {
        this.corrtype = corrtype;
    }
}