package com.kylin.quantization.model;

public class IndexFundCorr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEX_FUND_CORR.fundcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String fundcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEX_FUND_CORR.indexcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private String indexcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEX_FUND_CORR.correlationindex
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    private Long correlationindex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEX_FUND_CORR.fundcode
     *
     * @return the value of INDEX_FUND_CORR.fundcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getFundcode() {
        return fundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEX_FUND_CORR.fundcode
     *
     * @param fundcode the value for INDEX_FUND_CORR.fundcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setFundcode(String fundcode) {
        this.fundcode = fundcode == null ? null : fundcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEX_FUND_CORR.indexcode
     *
     * @return the value of INDEX_FUND_CORR.indexcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public String getIndexcode() {
        return indexcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEX_FUND_CORR.indexcode
     *
     * @param indexcode the value for INDEX_FUND_CORR.indexcode
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setIndexcode(String indexcode) {
        this.indexcode = indexcode == null ? null : indexcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEX_FUND_CORR.correlationindex
     *
     * @return the value of INDEX_FUND_CORR.correlationindex
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public Long getCorrelationindex() {
        return correlationindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEX_FUND_CORR.correlationindex
     *
     * @param correlationindex the value for INDEX_FUND_CORR.correlationindex
     *
     * @mbg.generated Fri Jan 25 16:07:50 CST 2019
     */
    public void setCorrelationindex(Long correlationindex) {
        this.correlationindex = correlationindex;
    }
}